package lk.blacky.bakerymanagement.util;

public enum Routes {
    LOGIN,ADMINLOGIN,CASHIERLOGIN,CHEIFCOOKLOGIN,ADMINDASHBOARD,
    MANAGECUSTOMER,MANAGEPRODUCT,MANAGEEMPLOYEE,MANAGESUPPLIER,
    MANAGESTOCK,VIEWINCOMEREPORTS,VIEWMONTHLYINCOMEREPORTS,
    MONTHLYPRODUCTCATEGORY,MONTHLYPRODUCTSELLING,VIEWANNUALLYINCOMEREPORTS,ANNUALLYPRODUCTSALES,ANNUALLYSALESDATAILS,
    CASHIERDASHBOARD,MANAGECUSTOMERWHITHCASHEIR,
    MANAGEPRODUCTWITHCASHIER,PLACEORDER,CHEIFCOOKDASHBOARD,
    MANAGEPRODUCTWITHCHEIEFCOOK,MANAGESUPPLIERDETAILSWITHCHEIFCOOK,
    MANAGESTOCKWITHCHEIFCOOK,MANAGERECIPE,VIEWRECIPE,
    ADMINSIGNUP,CASHIERSIGNUP,CHEIFCOOKSIGNUP,ADMINFORGOTPASSWORD,CASHIERFORGOTPASSWORD,CHIEFCOOKFORGOTPASSWORD,
    ADMINCUSTOMERVIEW,ADMINPRODUCTVIEW,ADMINEMPLOYEEVIEW,ADMINSUPPLIERVIEW,CASHIERVIEWCUSTOMER,CASHIERVIEWPRODUCT,
    MANAGEITEMS,CHEIFCOOKVIEWITEM,CHEIFCOOKVIEWSTOCK,CHIEFCOOKVIEWPRODUCT,CHEIFCOOKVIEWSUPPLIER
}
